version: '3.7'
services:
   api:
      build:
         context: ./backend
         dockerfile: Dockerfile
      depends_on:
         - db
      ports:
         - "5000:5000"
      environment: 
         STAGE: dev
         DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/sythesia_tasks"
      volumes:
         - ./backend:/api
      networks: 
         - backend

   client:
      build:
         context: ./frontend
         dockerfile: Dockerfile
      tty: true
      ports:
         - "3000:3000"
      volumes:
         - ./frontend:/app
         - /app/node_modules
      networks:
         - frontend

   db:
      image: postgres
      container_name: postgres
      restart: unless-stopped
      environment:
         - POSTGRES_DB=sythesia_tasks
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
      volumes:
         - db-data:/var/lib/postgresql/data
      networks:
         - backend

      ports:
         - "5432:5432"

volumes:
   db-data:
networks:
   frontend:
      driver: bridge
   backend:
      driver: bridge
