"""Update tasks model

Revision ID: 1935154fc97f
Revises: e782fd4d1864
Create Date: 2021-04-06 20:25:27.690215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1935154fc97f'
down_revision = 'e782fd4d1864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('private_id', sa.String(length=36), nullable=False))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_tasks_private_id'), 'tasks', ['private_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_private_id'), table_name='tasks')
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('tasks', 'private_id')
    # ### end Alembic commands ###
